name: Notificación Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js y ejecutar el programa
      - name: Ejecutar Hola Mundo
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node index.js

      # Enviar notificación a ntfy.sh
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "Se realizó un push a main: Hola Mundo ejecutado ✅" https://ntfy.sh/devops-itla
